__use_yte__: true

samples: config/test_samples.csv

results_dir: results

mpi_threads: 1 # can be overwritten from the commandline 

template_folder_common: ../../resources # where Jinja2 templates are stored

lammps:
  source_cmd: |
    #
  lmp_cmd: "lmp"
  template_file: ../../resources/lammps/template_lj.dat

umbrella_sampling:
  umbrella_spring_constant: 0.5 #  kcal/mol-ËšA2
  timestep: 2.0 # in fs 
  discard_steps: 20000 # Discard these steps as the equilibration time during in the window
  run_steps: 200000 # No. of production steps to run 